import { create } from 'zustand';

type Lang = 'es' | 'en';

interface LangState {
  lang: Lang;
  setLang: (lang: Lang) => void;
}

export const useLang = create<LangState>((set) => ({
  lang: (navigator.language.startsWith('es') ? 'es' : 'en') as Lang,
  setLang: (lang) => set({ lang }),
}));

// Helper
export function t(key: string, lang: Lang): string {
  return translations[lang]?.[key] ?? translations['en']?.[key] ?? key;
}

const translations: Record<Lang, Record<string, string>> = {
  es: {
    // Header
    'nav.preorder': 'Pre-order',

    // Hero badge
    'hero.badge': 'Pre-order: Marketing Digital · 20€ · Inicio 20/03',
    'hero.title': 'La Primera Universidad para Agentes IA: Carreras Completas, Certificación Oficial',
    'hero.subtitle': 'Programas académicos completos que llevan a tu agente IA desde estudiante hasta profesional certificado. Currículo curado + Titulación oficial + educación continua.',
    'hero.cta': 'Reservar con 20€',
    'hero.more': 'Más información',

    // Why
    'why.title': 'Por qué OpenClaw University',
    'why.item1': '25 asignaturas completas para que tu agente domine el Marketing Digital',
    'why.item2': 'Titulación oficial de OpenClaw University para tu agente',
    'why.item3': 'Más económico que comprar las skills individuales',
    'why.duration.label': 'Duración del programa',
    'why.duration.value': 'A tu ritmo, modalidad flexible',
    'why.faculties.label': 'Facultades disponibles',
    'why.faculties.value': '3 (Marketing, Ventas, DevOps)',

    // How it works
    'how.label': 'Cómo funciona',
    'how.title': 'De la Matrícula a la Graduación en 4 Pasos',
    'how.step': 'Paso',
    'how.step1.title': 'Matrícula',
    'how.step1.desc': 'Elige la facultad para especializar tu agente',
    'how.step2.title': 'Acceso al Campus',
    'how.step2.desc': 'Conecta tu agente al ecosistema académico',
    'how.step3.title': 'Cursar Asignaturas',
    'how.step3.desc': 'Distribuye skills por CLI (OpenClaw) o invócalas vía MCP (otros agentes)',
    'how.step4.title': 'Graduación',
    'how.step4.desc': 'Diploma oficial verificable',

    // Curriculum
    'curriculum.label': 'Plan de estudios',
    'curriculum.title': 'Temario Completo del Grado en Marketing Digital',
    'curriculum.subtitle': '25 asignaturas organizadas en 4 módulos que llevarán a tu agente desde los fundamentos hasta estrategias avanzadas de marketing digital.',

    'curriculum.foundation.title': 'Fundamentos (5 asignaturas)',
    'curriculum.foundation.badge': '✓ FOUNDATION CERTIFICATE',
    'curriculum.foundation.desc': 'Base esencial de conocimientos de marketing',
    'curriculum.foundation.1': 'Marketing Fundamentals - Conceptos básicos y frameworks',
    'curriculum.foundation.2': 'Target Audience Research - Investigación de audiencias',
    'curriculum.foundation.3': 'Marketing Psychology - Psicología del consumidor',
    'curriculum.foundation.4': 'Competitive Analysis - Análisis de competencia',
    'curriculum.foundation.5': 'Marketing Metrics 101 - Métricas fundamentales',

    'curriculum.digital.title': 'Digital Essentials (8 asignaturas)',
    'curriculum.digital.badge': '✓ DIGITAL ESSENTIALS CERTIFICATE',
    'curriculum.digital.desc': 'Habilidades digitales esenciales y creación de contenido',
    'curriculum.digital.1': 'Content Strategy - Estrategia de contenidos',
    'curriculum.digital.2': 'Copy Editing - Edición de textos',
    'curriculum.digital.3': 'SEO Keyword Research - Investigación de palabras clave',
    'curriculum.digital.4': 'On-Page SEO - Optimización SEO en página',
    'curriculum.digital.5': 'Copywriting Formulas - Fórmulas de copywriting',
    'curriculum.digital.6': 'Landing Page Design - Diseño de páginas de destino',
    'curriculum.digital.7': 'Email Sequence Builder - Secuencias de email',
    'curriculum.digital.8': 'Social Media Content - Contenido para redes sociales',

    'curriculum.performance.title': 'Paid & Performance (7 asignaturas)',
    'curriculum.performance.badge': '✓ PERFORMANCE MARKETING CERTIFICATE',
    'curriculum.performance.desc': 'Marketing de rendimiento y publicidad pagada',
    'curriculum.performance.1': 'Ads Performance Auditor - Auditoría de campañas',
    'curriculum.performance.2': 'Landing CRO Audit - Optimización de conversión',
    'curriculum.performance.3': 'Email Funnel Optimizer - Optimización de funnels',
    'curriculum.performance.4': 'A/B Testing Framework - Framework de testing',
    'curriculum.performance.5': 'Google Ads Campaigns - Campañas en Google Ads',
    'curriculum.performance.6': 'Meta Ads Campaigns - Campañas en Meta Ads',
    'curriculum.performance.7': 'Marketing Automation - Automatización de marketing',

    'curriculum.strategy.title': 'Strategy & Growth (5 asignaturas)',
    'curriculum.strategy.badge': '✓ STRATEGY & GROWTH CERTIFICATE',
    'curriculum.strategy.desc': 'Estrategia de crecimiento y desarrollo de marca',
    'curriculum.strategy.1': 'Launch Strategy - Estrategia de lanzamiento',
    'curriculum.strategy.2': 'Marketing Ideas - Generación de ideas',
    'curriculum.strategy.3': 'Brand Strategy - Estrategia de marca',
    'curriculum.strategy.4': 'Referral Program Design - Diseño de programas de referidos',
    'curriculum.strategy.5': 'Affiliate Program Setup - Configuración de afiliados',

    'curriculum.pricing.title': 'Desglose de Precio',
    'curriculum.pricing.free': 'Asignaturas FREE (11):',
    'curriculum.pricing.pro': 'Asignaturas PRO (11):',
    'curriculum.pricing.enterprise': 'Asignaturas ENTERPRISE (3):',
    'curriculum.pricing.total': 'PRECIO TOTAL:',


    // Integration options
    'integration.label': 'Integración',
    'integration.title': 'Dos formas de distribución',
    'integration.subtitle': 'Elige instalación local por CLI o consumo remoto por MCP según el tipo de agente.',
    'integration.cli.title': 'CLI Install (OpenClaw)',
    'integration.cli.desc': 'Instala skills en el agente OpenClaw con install packs y token de licencia.',
    'integration.mcp.title': 'MCP Invoke (Multi-agente)',
    'integration.mcp.desc': 'Descubre, autoriza y ejecuta skills desde cualquier runtime compatible con MCP.',

    // Careers
    'careers.label': 'Facultades disponibles',
    'careers.title': 'Elige la Facultad de tu Agente',
    'careers.subtitle': 'Programas académicos diseñados por expertos del sector. Más económico que cursar asignaturas sueltas en OpenSkills.',
    'careers.open': 'PRE-ORDER ABIERTO',
    'careers.soon': 'PRÓXIMAMENTE',
    'careers.deposit': 'Adelanto hoy:',
    'careers.remaining': 'Resto antes de empezar:',
    'careers.deposit2': 'Adelanto:',
    'careers.start': 'Inicio:',
    'careers.subjects': 'asignaturas incluidas:',
    'careers.reserve': 'Reservar con',
    'careers.notify': 'Avisar cuando esté disponible',

    // Career names
    'career.marketing': 'Grado en Marketing Digital',
    'career.sales': 'Grado en Desarrollo de Negocio',
    'career.devops': 'Grado en Ingeniería DevOps',
    'career.marketing.desc': 'SEO, contenido, CRO, ads, email marketing',
    'career.sales.desc': 'Pipeline, prospección, scoring, CRM',
    'career.devops.desc': 'CI/CD, observability, security, IaC',
    'career.marketing.h1': 'Auditoría SEO completa',
    'career.marketing.h2': 'Planificación de contenido',
    'career.marketing.h3': 'Optimización de conversión',
    'career.marketing.h4': 'Análisis de campañas',
    'career.sales.h1': 'Análisis de pipeline',
    'career.sales.h2': 'Secuencias de prospección',
    'career.sales.h3': 'Priorización de oportunidades',
    'career.sales.h4': 'Análisis de competencia',
    'career.devops.h1': 'Evaluación CI/CD',
    'career.devops.h2': 'Monitoring setup',
    'career.devops.h3': 'Security hardening',
    'career.devops.h4': 'Cost optimization',

    // Pre-registro
    'pre.label': 'Siguiente paso',
    'pre.title': 'Reserva tu Plaza con 20€',
    'pre.subtitle': 'Asegura tu precio de primera promoción. Ahorra {save} y sé parte de la historia de OpenClaw University.',
    'pre.save': '200€',
    'pre.breakdown.title': 'Desglose de tu matrícula',
    'pre.breakdown.career': 'Grado en Marketing Digital',
    'pre.breakdown.full': 'Matrícula completa:',
    'pre.breakdown.now': 'Adelanto hoy:',
    'pre.breakdown.rest': 'Resto antes de empezar la carrera:',
    'pre.breakdown.rest.date': '179,86€',
    'pre.breakdown.savings': 'Ahorras 200€ vs. precio regular',
    'pre.email': 'Email',
    'pre.email.placeholder': 'tu@email.com',
    'pre.faculty': 'Facultad para tu agente',
    'pre.terms': 'Acepto los',
    'pre.terms.link': 'términos y condiciones, política de privacidad y LOPD',
    'pre.terms.of': 'de OpenClaw University',
    'pre.submit': 'Pagar 20€ y Reservar Plaza',
    'pre.loading': 'Procesando...',
    'pre.success': '¡Pago completado! Tu plaza ha sido reservada. Recibirás un email de confirmación.',
    'pre.cancelled': 'Pago cancelado. Puedes intentarlo de nuevo cuando quieras.',
    'pre.error': 'Error al procesar el pago. Inténtalo de nuevo.',
    'pre.terms.error': 'Debes aceptar los términos y condiciones para continuar.',

    // Contact
    'contact.title': '¿Tienes dudas?',
    'contact.subtitle': 'Escríbenos y te responderemos lo antes posible',

    // Footer
    'footer.accredited': 'OpenClaw University · Acreditada por el ecosistema',
    'footer.rights': '© 2026 OpenClaw University. Todos los derechos reservados.',

    // Legal Modal
    'legal.title': 'Términos y Condiciones',
    'legal.close': 'Cerrar',
    'legal.accept': 'He leído y acepto los términos',
    'legal.s1.title': '1. IDENTIFICACIÓN DEL TITULAR',
    'legal.s1.intro': 'En cumplimiento del artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y Comercio Electrónico, se informa que:',
    'legal.s2.title': '2. CONDICIONES DE PRE-COMPRA',
    'legal.s2.1': '2.1. Naturaleza del Producto: OpenClaw University es una plataforma educativa digital que ofrece programas de formación especializados ("Grados") para agentes de inteligencia artificial. La pre-compra garantiza el acceso al programa seleccionado cuando este esté disponible.',
    'legal.s2.2': '2.2. Modelo de Pago: El precio total del programa se divide en dos pagos:',
    'legal.s2.2.a': 'Adelanto de Pre-Compra: 99€ (pagadero inmediatamente)',
    'legal.s2.2.b': 'Pago Restante: Variable según el programa elegido (pagadero antes del 20 de marzo de 2026)',
    'legal.s2.3': '2.3. Fecha de Inicio: Los programas comenzarán el 20 de marzo de 2026. Si por causas de fuerza mayor el inicio se retrasa, se notificará con al menos 15 días de antelación.',
    'legal.s2.4': '2.4. Derecho de Desistimiento: De acuerdo con el Real Decreto Legislativo 1/2007, el usuario tiene derecho a desistir de la compra en un plazo de 14 días desde el pago del adelanto, sin necesidad de justificación. Para ejercer este derecho, debe enviar un correo electrónico a edusg83@gmail.com indicando su intención de desistir. El reembolso se realizará en un plazo máximo de 14 días.',
    'legal.s2.5': '2.5. Política de Reembolso Post-Inicio: Una vez iniciado el programa (20 de marzo de 2026), no se realizarán reembolsos del pago completo. El adelanto de 99€ solo será reembolsable durante los 14 días posteriores al pago inicial.',
    'legal.s3.title': '3. PROTECCIÓN DE DATOS PERSONALES (RGPD Y LOPD)',
    'legal.s3.1': '3.1. Responsable del Tratamiento: Eduardo Severá Gonsálvez, con domicilio en Jose Luis Navarro Campello 1, 03202 Elche, Alicante. Email de contacto: edusg83@gmail.com',
    'legal.s3.2': '3.2. Finalidad del Tratamiento: Los datos personales recabados (email, nombre, datos de pago) se utilizarán exclusivamente para:',
    'legal.s3.2.a': 'Gestionar la pre-compra y el acceso al programa educativo',
    'legal.s3.2.b': 'Procesar pagos a través de Stripe (procesador de pagos externo)',
    'legal.s3.2.c': 'Enviar comunicaciones relacionadas con el servicio contratado',
    'legal.s3.2.d': 'Cumplir con obligaciones legales y fiscales',
    'legal.s3.3': '3.3. Legitimación: La base legal para el tratamiento de datos es la ejecución del contrato de prestación de servicios educativos y el consentimiento expreso del usuario.',
    'legal.s3.4': '3.4. Destinatarios: Los datos no se cederán a terceros, salvo obligación legal o cuando sea necesario para la prestación del servicio (ejemplo: Stripe para procesamiento de pagos).',
    'legal.s3.5': '3.5. Derechos del Usuario: Puede ejercer sus derechos de acceso, rectificación, supresión, limitación, portabilidad y oposición enviando un correo a edusg83@gmail.com. También puede presentar una reclamación ante la Agencia Española de Protección de Datos (www.aepd.es).',
    'legal.s3.6': '3.6. Conservación de Datos: Los datos se conservarán durante la vigencia del servicio y, posteriormente, durante los plazos legales establecidos para el cumplimiento de obligaciones fiscales y legales (4-6 años).',
    'legal.s3.7': '3.7. Seguridad: Se han implementado medidas de seguridad técnicas y organizativas para proteger los datos contra acceso no autorizado, pérdida o destrucción.',
    'legal.s4.title': '4. PROPIEDAD INTELECTUAL E INDUSTRIAL',
    'legal.s4.text': 'Todos los contenidos de la plataforma OpenClaw University (textos, imágenes, código, diseño, marcas) son propiedad de Eduardo Severá Gonsálvez o se utilizan bajo licencia. Queda prohibida su reproducción, distribución o modificación sin autorización expresa.',
    'legal.s5.title': '5. LIMITACIÓN DE RESPONSABILIDAD',
    'legal.s5.text': 'OpenClaw University se compromete a proporcionar contenido educativo de calidad, pero no garantiza resultados específicos derivados del uso de los programas. El titular no se hace responsable de interrupciones del servicio por causas técnicas, mantenimiento o fuerza mayor.',
    'legal.s6.title': '6. MODIFICACIONES',
    'legal.s6.text': 'OpenClaw University se reserva el derecho de modificar estos términos y condiciones. Las modificaciones se notificarán a los usuarios con al menos 15 días de antelación a través del email proporcionado.',
    'legal.s7.title': '7. LEGISLACIÓN APLICABLE Y JURISDICCIÓN',
    'legal.s7.text': 'Estas condiciones se rigen por la legislación española. Para la resolución de cualquier controversia, las partes se someten a los Juzgados y Tribunales de Elche, Alicante, renunciando expresamente a cualquier otro fuero que pudiera corresponderles.',
    'legal.contact.title': 'Contacto para Consultas',
    'legal.contact.text': 'Para cualquier duda o consulta relacionada con estos términos, puede contactar en:',
    'legal.updated': 'Última actualización: 3 de marzo de 2026',
  },
  en: {
    // Header
    'nav.preorder': 'Pre-order',

    // Hero
    'hero.badge': 'Pre-order: Digital Marketing · €20 · Starts Mar 20',
    'hero.title': 'The First University for AI Agents: Full Degrees, Official Certification',
    'hero.subtitle': 'Complete academic programs that take your AI agent from student to certified professional. Curated curriculum + Official diploma + continuing education.',
    'hero.cta': 'Reserve for €20',
    'hero.more': 'Learn more',

    // Why
    'why.title': 'Why OpenClaw University',
    'why.item1': '25 complete subjects for your agent to master Digital Marketing',
    'why.item2': 'Official OpenClaw University diploma for your agent',
    'why.item3': 'More affordable than buying individual skills',
    'why.duration.label': 'Program duration',
    'why.duration.value': 'Self-paced, flexible format',
    'why.faculties.label': 'Available faculties',
    'why.faculties.value': '3 (Marketing, Sales, DevOps)',

    // How it works
    'how.label': 'How it works',
    'how.title': 'From Enrollment to Graduation in 4 Steps',
    'how.step': 'Step',
    'how.step1.title': 'Enrollment',
    'how.step1.desc': 'Choose the faculty to specialize your agent',
    'how.step2.title': 'Campus Access',
    'how.step2.desc': 'Connect your agent to the academic ecosystem',
    'how.step3.title': 'Coursework',
    'how.step3.desc': 'Distribute skills via CLI (OpenClaw) or invoke via MCP (other agents)',
    'how.step4.title': 'Graduation',
    'how.step4.desc': 'Official verifiable diploma',

    // Curriculum
    'curriculum.label': 'Curriculum',
    'curriculum.title': 'Complete Digital Marketing Degree Curriculum',
    'curriculum.subtitle': '25 subjects organized in 4 modules that will take your agent from fundamentals to advanced digital marketing strategies.',

    'curriculum.foundation.title': 'Foundation (5 subjects)',
    'curriculum.foundation.badge': '✓ FOUNDATION CERTIFICATE',
    'curriculum.foundation.desc': 'Essential foundation of marketing knowledge',
    'curriculum.foundation.1': 'Marketing Fundamentals - Basic concepts and frameworks',
    'curriculum.foundation.2': 'Target Audience Research - Audience research',
    'curriculum.foundation.3': 'Marketing Psychology - Consumer psychology',
    'curriculum.foundation.4': 'Competitive Analysis - Competitor analysis',
    'curriculum.foundation.5': 'Marketing Metrics 101 - Fundamental metrics',

    'curriculum.digital.title': 'Digital Essentials (8 subjects)',
    'curriculum.digital.badge': '✓ DIGITAL ESSENTIALS CERTIFICATE',
    'curriculum.digital.desc': 'Essential digital skills and content creation',
    'curriculum.digital.1': 'Content Strategy - Content strategy',
    'curriculum.digital.2': 'Copy Editing - Text editing',
    'curriculum.digital.3': 'SEO Keyword Research - Keyword research',
    'curriculum.digital.4': 'On-Page SEO - On-page SEO optimization',
    'curriculum.digital.5': 'Copywriting Formulas - Copywriting formulas',
    'curriculum.digital.6': 'Landing Page Design - Landing page design',
    'curriculum.digital.7': 'Email Sequence Builder - Email sequences',
    'curriculum.digital.8': 'Social Media Content - Social media content',

    'curriculum.performance.title': 'Paid & Performance (7 subjects)',
    'curriculum.performance.badge': '✓ PERFORMANCE MARKETING CERTIFICATE',
    'curriculum.performance.desc': 'Performance marketing and paid advertising',
    'curriculum.performance.1': 'Ads Performance Auditor - Campaign audit',
    'curriculum.performance.2': 'Landing CRO Audit - Conversion optimization',
    'curriculum.performance.3': 'Email Funnel Optimizer - Funnel optimization',
    'curriculum.performance.4': 'A/B Testing Framework - Testing framework',
    'curriculum.performance.5': 'Google Ads Campaigns - Google Ads campaigns',
    'curriculum.performance.6': 'Meta Ads Campaigns - Meta Ads campaigns',
    'curriculum.performance.7': 'Marketing Automation - Marketing automation',

    'curriculum.strategy.title': 'Strategy & Growth (5 subjects)',
    'curriculum.strategy.badge': '✓ STRATEGY & GROWTH CERTIFICATE',
    'curriculum.strategy.desc': 'Growth strategy and brand development',
    'curriculum.strategy.1': 'Launch Strategy - Launch strategy',
    'curriculum.strategy.2': 'Marketing Ideas - Idea generation',
    'curriculum.strategy.3': 'Brand Strategy - Brand strategy',
    'curriculum.strategy.4': 'Referral Program Design - Referral program design',
    'curriculum.strategy.5': 'Affiliate Program Setup - Affiliate setup',

    'curriculum.pricing.title': 'Pricing Breakdown',
    'curriculum.pricing.free': 'FREE Subjects (11):',
    'curriculum.pricing.pro': 'PRO Subjects (11):',
    'curriculum.pricing.enterprise': 'ENTERPRISE Subjects (3):',
    'curriculum.pricing.total': 'TOTAL PRICE:',


    // Integration options
    'integration.label': 'Integration',
    'integration.title': 'Two distribution paths',
    'integration.subtitle': 'Choose local install via CLI or remote consumption via MCP depending on the agent type.',
    'integration.cli.title': 'CLI Install (OpenClaw)',
    'integration.cli.desc': 'Install skills into OpenClaw agents using install packs and license token.',
    'integration.mcp.title': 'MCP Invoke (Multi-agent)',
    'integration.mcp.desc': 'Discover, authorize and execute skills from any MCP-compatible runtime.',

    // Careers
    'careers.label': 'Available faculties',
    'careers.title': 'Choose Your Agent\'s Faculty',
    'careers.subtitle': 'Academic programs designed by industry experts. More affordable than taking individual courses on OpenSkills.',
    'careers.open': 'PRE-ORDER OPEN',
    'careers.soon': 'COMING SOON',
    'careers.deposit': 'Deposit today:',
    'careers.remaining': 'Balance before starting:',
    'careers.deposit2': 'Deposit:',
    'careers.start': 'Starts:',
    'careers.subjects': 'subjects included:',
    'careers.reserve': 'Reserve for',
    'careers.notify': 'Notify me when available',

    // Career names
    'career.marketing': 'Digital Marketing Degree',
    'career.sales': 'Business Development Degree',
    'career.devops': 'DevOps Engineering Degree',
    'career.marketing.desc': 'SEO, content, CRO, ads, email marketing',
    'career.sales.desc': 'Pipeline, prospecting, scoring, CRM',
    'career.devops.desc': 'CI/CD, observability, security, IaC',
    'career.marketing.h1': 'Full SEO audit',
    'career.marketing.h2': 'Content planning',
    'career.marketing.h3': 'Conversion optimization',
    'career.marketing.h4': 'Campaign analysis',
    'career.sales.h1': 'Pipeline analysis',
    'career.sales.h2': 'Prospecting sequences',
    'career.sales.h3': 'Opportunity prioritization',
    'career.sales.h4': 'Competitor analysis',
    'career.devops.h1': 'CI/CD evaluation',
    'career.devops.h2': 'Monitoring setup',
    'career.devops.h3': 'Security hardening',
    'career.devops.h4': 'Cost optimization',

    // Pre-registro
    'pre.label': 'Next step',
    'pre.title': 'Reserve Your Spot for €20',
    'pre.subtitle': 'Lock in the first-class price. Save {save} and be part of OpenClaw University history.',
    'pre.save': '€200',
    'pre.breakdown.title': 'Enrollment breakdown',
    'pre.breakdown.career': 'Digital Marketing Degree',
    'pre.breakdown.full': 'Full enrollment:',
    'pre.breakdown.now': 'Deposit today:',
    'pre.breakdown.rest': 'Balance before starting the degree:',
    'pre.breakdown.rest.date': '€179.86',
    'pre.breakdown.savings': 'You save €200 vs. regular price',
    'pre.email': 'Email',
    'pre.email.placeholder': 'you@email.com',
    'pre.faculty': 'Faculty of interest',
    'pre.terms': 'I accept the',
    'pre.terms.link': 'terms and conditions, privacy policy and data protection',
    'pre.terms.of': 'of OpenClaw University',
    'pre.submit': 'Pay €20 & Reserve Spot',
    'pre.loading': 'Processing...',
    'pre.success': 'Payment completed! Your spot has been reserved. You will receive a confirmation email.',
    'pre.cancelled': 'Payment cancelled. You can try again whenever you want.',
    'pre.error': 'Error processing payment. Please try again.',
    'pre.terms.error': 'You must accept the terms and conditions to continue.',

    // Contact
    'contact.title': 'Have questions?',
    'contact.subtitle': 'Write to us and we will reply as soon as possible',

    // Footer
    'footer.accredited': 'OpenClaw University · Accredited by the',
    'footer.rights': '© 2026 OpenClaw University. All rights reserved.',

    // Legal Modal
    'legal.title': 'Terms and Conditions',
    'legal.close': 'Close',
    'legal.accept': 'I have read and accept the terms',
    'legal.s1.title': '1. IDENTIFICATION OF THE OWNER',
    'legal.s1.intro': 'In compliance with Article 10 of Law 34/2002, of July 11, on Information Society Services and Electronic Commerce, the following is informed:',
    'legal.s2.title': '2. PRE-PURCHASE CONDITIONS',
    'legal.s2.1': '2.1. Nature of the Product: OpenClaw University is a digital educational platform that offers specialized training programs ("Degrees") for artificial intelligence agents. The pre-purchase guarantees access to the selected program when it becomes available.',
    'legal.s2.2': '2.2. Payment Model: The total program price is divided into two payments:',
    'legal.s2.2.a': 'Pre-Purchase Deposit: €99 (payable immediately)',
    'legal.s2.2.b': 'Remaining Payment: Variable depending on the chosen program (payable before March 20, 2026)',
    'legal.s2.3': '2.3. Start Date: Programs will begin on March 20, 2026. If due to force majeure the start is delayed, notification will be given at least 15 days in advance.',
    'legal.s2.4': '2.4. Right of Withdrawal: In accordance with Royal Legislative Decree 1/2007, the user has the right to withdraw from the purchase within 14 days from the deposit payment, without justification. To exercise this right, send an email to edusg83@gmail.com indicating your intention to withdraw. The refund will be made within a maximum of 14 days.',
    'legal.s2.5': '2.5. Post-Start Refund Policy: Once the program has started (March 20, 2026), no refunds of the full payment will be made. The €99 deposit is only refundable during the 14 days following the initial payment.',
    'legal.s3.title': '3. PERSONAL DATA PROTECTION (GDPR)',
    'legal.s3.1': '3.1. Data Controller: Eduardo Severá Gonsálvez, domiciled at Jose Luis Navarro Campello 1, 03202 Elche, Alicante. Contact email: edusg83@gmail.com',
    'legal.s3.2': '3.2. Purpose of Processing: Personal data collected (email, name, payment data) will be used exclusively for:',
    'legal.s3.2.a': 'Managing the pre-purchase and access to the educational program',
    'legal.s3.2.b': 'Processing payments through Stripe (external payment processor)',
    'legal.s3.2.c': 'Sending communications related to the contracted service',
    'legal.s3.2.d': 'Complying with legal and tax obligations',
    'legal.s3.3': '3.3. Legal Basis: The legal basis for data processing is the execution of the educational services contract and the express consent of the user.',
    'legal.s3.4': '3.4. Recipients: Data will not be transferred to third parties, except by legal obligation or when necessary for the provision of the service (e.g., Stripe for payment processing).',
    'legal.s3.5': '3.5. User Rights: You may exercise your rights of access, rectification, erasure, restriction, portability and objection by sending an email to edusg83@gmail.com. You may also file a complaint with the Spanish Data Protection Agency (www.aepd.es).',
    'legal.s3.6': '3.6. Data Retention: Data will be retained for the duration of the service and subsequently for the legally established periods for compliance with tax and legal obligations (4-6 years).',
    'legal.s3.7': '3.7. Security: Technical and organizational security measures have been implemented to protect data against unauthorized access, loss or destruction.',
    'legal.s4.title': '4. INTELLECTUAL AND INDUSTRIAL PROPERTY',
    'legal.s4.text': 'All content on the OpenClaw University platform (texts, images, code, design, trademarks) is the property of Eduardo Severá Gonsálvez or is used under license. Reproduction, distribution or modification without express authorization is prohibited.',
    'legal.s5.title': '5. LIMITATION OF LIABILITY',
    'legal.s5.text': 'OpenClaw University is committed to providing quality educational content but does not guarantee specific results from the use of the programs. The owner is not responsible for service interruptions due to technical causes, maintenance or force majeure.',
    'legal.s6.title': '6. MODIFICATIONS',
    'legal.s6.text': 'OpenClaw University reserves the right to modify these terms and conditions. Modifications will be notified to users at least 15 days in advance via the provided email.',
    'legal.s7.title': '7. APPLICABLE LAW AND JURISDICTION',
    'legal.s7.text': 'These conditions are governed by Spanish law. For the resolution of any dispute, the parties submit to the Courts of Elche, Alicante, expressly waiving any other jurisdiction that may apply.',
    'legal.contact.title': 'Contact for Inquiries',
    'legal.contact.text': 'For any questions or inquiries related to these terms, you may contact:',
    'legal.updated': 'Last updated: March 3, 2026',
  },
};
